using System.Collections.Generic;
using SqlMigrator.Core.Models;
using SqlMigrator.Core.Services.DataMove;
using Xunit;

namespace SqlMigrator.Tests;

public class CanonicalDdlTests
{
    private static CanonicalTable Orders()
    {
        return new CanonicalTable
        {
            Schema = "dbo",
            Name = "Orders",
            Columns = new List<CanonicalColumn>
            {
                new() { Name = "Id", Type = CanonicalType.Int32, IsPrimaryKey = true, IsIdentity = true, IsNullable = false },
                new() { Name = "Code", Type = CanonicalType.String, MaxLength = 50, IsUnicode = true, IsNullable = false, DefaultSql = "'X'" },
                new() { Name = "Total", Type = CanonicalType.Decimal, Precision = 10, Scale = 2, IsNullable = true },
                new() { Name = "Created", Type = CanonicalType.DateTime, Scale = 7, IsNullable = false, DefaultSql = "SYSUTCDATETIME()" },
                new() { Name = "RowId", Type = CanonicalType.Guid, IsNullable = false }
            },
            PrimaryKeyColumns = new List<string> { "Id" },
            ForeignKeys = new List<CanonicalForeignKey>
            {
                new()
                {
                    Name = "FK_Orders_Customers",
                    Columns = new List<string> { "Code" },
                    RefSchema = "dbo",
                    RefTable = "Customers",
                    RefColumns = new List<string> { "Code" }
                }
            }
        };
    }

    [Fact]
    public void EmitPostgres_QuotesAllAndIdentity()
    {
        var sql = CanonicalDdl.EmitPostgres(Orders(), out var warnings);

        Assert.Contains("CREATE TABLE \"dbo\".\"Orders\"", sql);
        Assert.Contains("\"Id\" INTEGER GENERATED BY DEFAULT AS IDENTITY", sql);
        Assert.Contains("\"Code\" VARCHAR(50) NOT NULL DEFAULT 'X'", sql);
        Assert.Contains("\"Total\" NUMERIC(10,2)", sql);
        Assert.Contains("\"Created\" TIMESTAMP(7)", sql);
        Assert.Contains("PRIMARY KEY (\"Id\")", sql);
        Assert.Contains("CONSTRAINT \"FK_Orders_Customers\" FOREIGN KEY (\"Code\")", sql);
        Assert.Contains("REFERENCES \"dbo\".\"Customers\" (\"Code\")", sql);
        Assert.DoesNotContain("SYSUTCDATETIME()", sql);
        Assert.Empty(warnings);
    }

    [Fact]
    public void EmitSqlite_SingleIntegerPkInline()
    {
        var sql = CanonicalDdl.EmitSqlite(Orders(), out var warnings);

        Assert.Contains("CREATE TABLE \"Orders\"", sql);
        Assert.Contains("\"Id\" INTEGER PRIMARY KEY", sql);
        Assert.Contains("\"RowId\" TEXT", sql);
        Assert.DoesNotContain("dbo", sql);
        Assert.NotEmpty(warnings);
    }

    [Fact]
    public void EmitSqlServer_RoundTripBasics()
    {
        var sql = CanonicalDdl.EmitSqlServer(Orders(), out var warnings);

        Assert.Contains("CREATE TABLE [dbo].[Orders]", sql);
        Assert.Contains("[Id] [INT] IDENTITY(1,1)".Replace("[INT]", "INT"), sql);
        Assert.Contains("[Code] NVARCHAR(50) NOT NULL DEFAULT 'X'", sql);
        Assert.Contains("PRIMARY KEY ([Id])", sql);
        Assert.Empty(warnings);
    }

    [Fact]
    public void TranslateDefault_UnknownFunction_DroppedWithWarning()
    {
        var (kept, warning) = CanonicalDdl.TranslateDefault(
            "dbo.fn_Default()", DatabaseEngine.PostgreSql);

        Assert.Null(kept);
        Assert.NotNull(warning);
    }

    [Theory]
    [InlineData("123", "123")]
    [InlineData("'abc'", "'abc'")]
    [InlineData("N'abc'", "'abc'")]
    [InlineData("GETDATE()", "CURRENT_TIMESTAMP")]
    public void TranslateDefault_CommonCases_Postgres(string input, string expected)
    {
        var (kept, warning) = CanonicalDdl.TranslateDefault(input, DatabaseEngine.PostgreSql);

        Assert.Equal(expected, kept);
        Assert.Null(warning);
    }

    [Theory]
    [InlineData("int", "int(11)", CanonicalType.Int32)]
    [InlineData("bigint", "bigint(20)", CanonicalType.Int64)]
    [InlineData("tinyint", "tinyint(1)", CanonicalType.Bool)]
    [InlineData("tinyint", "tinyint(4)", CanonicalType.Int16)]
    [InlineData("varchar", "varchar(50)", CanonicalType.String)]
    [InlineData("text", "text", CanonicalType.String)]
    [InlineData("decimal", "decimal(10,2)", CanonicalType.Decimal)]
    [InlineData("datetime", "datetime(6)", CanonicalType.DateTime)]
    [InlineData("timestamp", "timestamp", CanonicalType.DateTime)]
    [InlineData("json", "json", CanonicalType.Json)]
    [InlineData("blob", "blob", CanonicalType.Binary)]
    [InlineData("enum", "enum('a','b')", CanonicalType.String)]
    [InlineData("whatever", "whatever", CanonicalType.Unknown)]
    public void ParseMySql_MapsCommonTypes(string dataType, string columnType, CanonicalType expected)
    {
        Assert.Equal(expected, DbTypeMappers.ParseMySql(dataType, columnType).Type);
    }

    [Fact]
    public void ParseMySql_VarcharLengthAndDecimalPrecision()
    {
        var s = DbTypeMappers.ParseMySql("varchar", "varchar(50)");
        Assert.Equal(50, s.MaxLength);
        var d = DbTypeMappers.ParseMySql("decimal", "decimal(10,2)");
        Assert.Equal((byte)10, d.Precision);
        Assert.Equal((byte)2, d.Scale);
        var t = DbTypeMappers.ParseMySql("text", "text");
        Assert.Equal(-1, t.MaxLength);
    }

    [Fact]
    public void SqlServerSource_ToMySql_TypesAndDefaults()
    {
        // Khóa chiều SQL Server → MySQL: identity inline, guid, bool, json, text dài.
        var table = new CanonicalTable
        {
            Schema = "dbo",
            Name = "Orders",
            Columns = new List<CanonicalColumn>
            {
                new() { Name = "Id", Type = CanonicalType.Int32, IsPrimaryKey = true, IsIdentity = true, IsNullable = false },
                new() { Name = "Code", Type = CanonicalType.String, MaxLength = 50, IsUnicode = true, IsNullable = false, DefaultSql = "'X'" },
                new() { Name = "Total", Type = CanonicalType.Decimal, Precision = 10, Scale = 2, IsNullable = true },
                new() { Name = "Active", Type = CanonicalType.Bool, IsNullable = false, DefaultSql = "1" },
                new() { Name = "RowId", Type = CanonicalType.Guid, IsNullable = false },
                new() { Name = "Payload", Type = CanonicalType.Json, IsNullable = true },
                new() { Name = "Note", Type = CanonicalType.String, MaxLength = -1, IsNullable = true }
            },
            PrimaryKeyColumns = new List<string> { "Id" }
        };
        var sql = CanonicalDdl.EmitMySql(table, out var warnings);

        Assert.Contains("CREATE TABLE `Orders`", sql);
        Assert.Contains("`Id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY", sql);
        Assert.Contains("`Code` VARCHAR(50) NOT NULL DEFAULT 'X'", sql);
        Assert.Contains("`Total` DECIMAL(10,2)", sql);
        Assert.Contains("`Active` TINYINT(1) NOT NULL", sql);
        Assert.Contains("`RowId` CHAR(36) NOT NULL", sql);
        Assert.Contains("ENGINE=InnoDB", sql);
        Assert.NotEmpty(warnings); // schema dbo bị bỏ + json cần version mới.
    }

    [Fact]
    public void MySqlSource_ToSqlServer_RoundTrip()
    {
        // Khóa chiều MySQL → SQL Server: parse information_schema rồi emit lại.
        var id = DbTypeMappers.ParseMySql("int", "int(11)");
        var name = DbTypeMappers.ParseMySql("varchar", "varchar(100)");
        var created = DbTypeMappers.ParseMySql("datetime", "datetime(6)");
        var table = new CanonicalTable
        {
            Schema = "shop",
            Name = "customers",
            Columns = new List<CanonicalColumn>
            {
                new() { Name = "id", Type = id.Type, IsPrimaryKey = true, IsIdentity = true, IsNullable = false },
                new() { Name = "name", Type = name.Type, MaxLength = name.MaxLength, IsNullable = false },
                new() { Name = "created", Type = created.Type, Scale = created.Scale, IsNullable = false }
            },
            PrimaryKeyColumns = new List<string> { "id" }
        };
        var sql = CanonicalDdl.EmitSqlServer(table, out var warnings);

        Assert.Contains("CREATE TABLE [shop].[customers]", sql);
        Assert.Contains("INT IDENTITY(1,1)", sql);
        Assert.Contains("NVARCHAR(100)", sql);
        Assert.Contains("DATETIME2(6)", sql);
        Assert.Empty(warnings);
    }

    [Theory]
    [InlineData(CanonicalType.Money, true)]
    [InlineData(CanonicalType.DateTimeTz, true)]
    [InlineData(CanonicalType.Json, true)]
    [InlineData(CanonicalType.Int32, false)]
    [InlineData(CanonicalType.Bool, false)]
    public void ConvertTo_MySql_Warnings(CanonicalType type, bool expectWarning)
    {
        var (_, _, _, _, warning) = DbTypeMappers.ConvertTo(
            type, 0, 0, 0, DatabaseEngine.MySql);

        Assert.Equal(expectWarning, warning != null);
    }

    [Fact]
    public void PgSource_ToSqlServer_TypesAndDefaults()
    {
        // Khóa chiều ngược PG → SQL Server: timestamptz/uuid/boolean/jsonb/text.
        CanonicalColumn Col(string name, string pgType, string? def = null)
        {
            var spec = DbTypeMappers.ParsePostgres(pgType);
            return new CanonicalColumn
            {
                Name = name, Type = spec.Type, MaxLength = spec.MaxLength,
                Precision = spec.Precision, Scale = spec.Scale,
                IsNullable = true, DefaultSql = def
            };
        }
        var table = new CanonicalTable
        {
            Schema = "public",
            Name = "events",
            Columns = new List<CanonicalColumn>
            {
                Col("ts", "timestamp with time zone"),
                Col("uid", "uuid"),
                Col("active", "boolean", "true"),
                Col("payload", "jsonb"),
                Col("note", "text")
            }
        };
        var sql = CanonicalDdl.EmitSqlServer(table, out var warnings);

        Assert.Contains("DATETIMEOFFSET", sql);
        Assert.Contains("UNIQUEIDENTIFIER", sql);
        Assert.Contains("BIT DEFAULT 1", sql);
        Assert.Contains("NVARCHAR(MAX)", sql);
        Assert.NotEmpty(warnings); // jsonb về SQL Server phải có cảnh báo.
    }

    [Theory]
    [InlineData("CURRENT_TIMESTAMP", "GETDATE()")]
    [InlineData("SYSUTCDATETIME()", "SYSUTCDATETIME()")]
    [InlineData("true", "1")]
    [InlineData("false", "0")]
    [InlineData("N'abc'", "N'abc'")]
    [InlineData("gen_random_uuid()", "NEWID()")]
    public void TranslateDefault_CommonCases_SqlServer(string input, string expected)
    {
        var (kept, warning) = CanonicalDdl.TranslateDefault(input, DatabaseEngine.SqlServer);

        Assert.Equal(expected, kept);
        Assert.Null(warning);
    }

    [Fact]
    public void SqliteSource_ToSqlServer_BasicTypes()
    {
        // Khóa chiều ngược SQLite → SQL Server qua affinity TEXT/INTEGER/REAL.
        Assert.Equal(CanonicalType.String, DbTypeMappers.ParseSqlite("TEXT").Type);
        Assert.Equal(CanonicalType.Int64, DbTypeMappers.ParseSqlite("INTEGER").Type);
        Assert.Equal(CanonicalType.Double, DbTypeMappers.ParseSqlite("REAL").Type);
        var table = new CanonicalTable
        {
            Name = "notes",
            Columns = new List<CanonicalColumn>
            {
                new() { Name = "Id", Type = CanonicalType.Int64, IsNullable = false },
                new() { Name = "Body", Type = CanonicalType.String, MaxLength = -1, IsNullable = true },
                new() { Name = "Score", Type = CanonicalType.Double, IsNullable = true }
            },
            PrimaryKeyColumns = new List<string> { "Id" }
        };
        var sql = CanonicalDdl.EmitSqlServer(table, out var warnings);

        Assert.Contains("BIGINT", sql);
        Assert.Contains("NVARCHAR(MAX)", sql);
        Assert.Contains("FLOAT(53)", sql);
        Assert.Single(warnings); // thiếu schema → cảnh báo dùng dbo mặc định.
    }
}
